version: '3'

services:
    db:
        container_name: db
        image: mysql
        ports:
            - 127.0.0.1:3306:3306
        networks:
            - appnet
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    php:
        container_name: php
        build: php7-fpm
        ports:
            - 127.0.0.1:9000:9000
        networks:
            - appnet
        links:
            - db:mysqldb
        volumes:
            - ${SYMFONY_APP_VOLUME}:/var/www/symfony
    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 80:80
        networks:
            - appnet
        links:
            - php
        volumes_from:
            - php
networks:
  appnet:
      driver: "bridge"
